from typing import Final

GRID_SIZE: Final = 50

STARTING_POPULATION_SIZE = 20
MAX_POPULATION_CLUSTERS: Final = 6
CROSSOVER_RATE: Final = 0.8
MUTATION_RATE: Final = 0.09 / (MAX_POPULATION_CLUSTERS**2)

GENERATIONS: Final = 60
